### ISSUE TITLE
Rename top-level package from open_feature to openfeature?

### ISSUE THREAD

**Issue by federicobond** [open-feature/python-sdk#181]
Should we rename the top-level package for the sdk from `open_feature` to `openfeature`?

The `opentelemetry` sdk does not use an underscore either, as is the case for most common Python packages which come from combined-word names (see `matplotlib`, `numpy`, `pytorch`, `tensorflow`)

This is of course a breaking change, but since we are revamping our whole package structure for this release, it's no more breaking than the rest of the changes that we are introducing.

I'm curious to hear your thoughts on this!

**Comment by toddbaert** [comment]
Great question. Both are acceptable, but we _tend_ to prefer one work `openfeature` over `open feature`/`open_feature`/`open-feature`. Since we're already breaking the package names, it might be a good time to change this.

https://openfeature.dev/docs/reference/concepts/provider#naming-recommendations

We should maybe promote this naming recommendation section to somewhere more general.
