### ISSUE TITLE
Implement wrapper for packaging and dependency management

### ISSUE THREAD

**Issue by tcarrio** [open-feature/python-sdk#59]
Implement an OTS python wrapper for packaging and dependency management (e.g. [Pipenv](https://pipenv.pypa.io/en/latest/index.html) or [Poetry](https://github.com/python-poetry/poetry))

**Comment by matthewelwell** [comment]
I think that we should explore other options here as well as pipenv for our requirements. I hold a slight grudge against `pipenv` due to it being previously unmaintained for a number of years and a number of niggly bugs. 

I have previously used [poetry](https://github.com/python-poetry/poetry) as an alternative which I found was much nicer to use - although it looks like the issue count against their repo is also rather high! 

I've updated the name of this issue to reflect this, rather than specifying the tool itself.

**Comment by tcarrio** [comment]
> it looks like the issue count against their repo is also rather high!

Filtering to just bugs there appear to be nearly 300 open.
